name: Upload Python Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      disable_publish:
        description: "Disable publish to PyPI"
        required: false
        type: boolean

jobs:
  build_binary_manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_24_x86_64

    strategy:
      matrix:
        python-version:
          - cp37-cp37m
          - cp38-cp38
          - cp39-cp39
          - cp310-cp310

    steps:
    - uses: actions/checkout@v2

    - name: Build Python wheels
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
         /opt/python/$PYTHON_VERSION/bin/python -m build --wheel

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.whl


  build_source:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python setup.py sdist

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.tar.gz

  publish:
    needs: [build_source, build_binary_manylinux]
    if: github.event.inputs.disable_publish == 'false'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist/

    - name: Publish package to PyPI
      # All files in dist/ are published
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
