name: Upload Python Package to TestPyPI

on:
  push:

env:
  TEST_PACKAGE_NAME: MulensModel-test
  TEST_PYPI_URL: https://test.pypi.org/legacy/

jobs:
  build_wheels:
    name: ${{ matrix.os }} ${{ matrix.cibw_archs }} ${{ matrix.cibw_build }} (Test)
    runs-on: ${{ matrix.os }}
    env:
      MULENSMODEL_PACKAGE_NAME: ${{ env.TEST_PACKAGE_NAME }}
      CIBW_ENVIRONMENT: MULENSMODEL_PACKAGE_NAME=${{ env.TEST_PACKAGE_NAME }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cibw_archs: [auto64, arm64]
        cibw_build: [cp38-*, cp39-*, cp310-*, cp311-*]
        cibw_skip: [pp*]
        exclude:
          - os: ubuntu-latest
            cibw_archs: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_SKIP: ${{ matrix.cibw_skip }}

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl

  build_source:
    name: Build sdist (Test)
    runs-on: ubuntu-latest
    env:
      MULENSMODEL_PACKAGE_NAME: ${{ env.TEST_PACKAGE_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist
        run: python -m build --sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-cibw-sdist
          path: dist/*.tar.gz

  publish:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: [build_wheels, build_source]
    env:
      TEST_PACKAGE_NAME: ${{ env.TEST_PACKAGE_NAME }}
      TEST_PYPI_URL: ${{ env.TEST_PYPI_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: test-cibw-*
          path: dist
          merge-multiple: true

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: ${{ env.TEST_PYPI_URL }}
          packages-dir: dist
