name: Tests
on:
  push:
    branches:
      - 'binary_convergence_shear'

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.5'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.5
    - name: Get requirements
      run: |
        python -m pip install -U pip
        python -m pip install -U -r requirements.txt
    - name: Setup package
      run: |
        python setup.py install
    - name: Test suite install
      run: |
        python -m pip install -U pytest
        python -m pip install -U pytest-cov
        python -m pip install -U pytest-github-actions-annotate-failures
    - name: Run tests
      run: |
        python -m pytest --exitfirst --verbose --failed-first --cov=. --cov-report xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
